from typing import List
from backend.utils import get_agent_response_with_metadata, RecipeRequest

dimensions = [
    "party_size",
    "dietary_restrictions",
    "cuisine_type",
    "user_persona",
    "scenario",
]

party_size_examples = ["1", "2", "3", "4", "5", "6", "7", "8", "9+"]
dietary_restrictions_examples = [
    "vegan",
    "vegetarian",
    "gluten-free",
    "dairy-free",
    "halal",
    "kosher",
    "shellfish-free",
    "peanut-free",
    "tree-nut-free",
    "soy-free",
    "egg-free",
    "gluten-free",
    "dairy-free",
]

cuisine_type_examples = [
    "American",
    "Italian",
    "Mexican",
    "Japanese",
    "Chinese",
    "Indian",
    "Thai",
    "Mediterranean",
    "French",
    "Greek",
    "Spanish",
    "Korean",
    "Vietnamese",
    "Indian",
]
user_persona_examples = [
    "foodie",
    "single",
    "couple",
    "group",
    "party",
    "date",
]

scenario_examples = [
    "clearly specified and feasible",
    "ambiguous or unclear request",
    "out of scope",
]

# Additional dimension examples
additional_party_sizes = [
    "2-3",
    "4-6",
    "7-9",
    "10-12",
    "13-15",
    "16-20",
    "family of 4",
    "small gathering",
    "large gathering",
]
additional_dietary_restrictions = [
    "low-carb",
    "keto",
    "paleo",
    "whole30",
    "low-sodium",
    "low-fat",
    "high-protein",
    "raw",
    "pescatarian",
    "flexitarian",
    "low-FODMAP",
    "anti-inflammatory",
    "diabetic-friendly",
    "heart-healthy",
    "low-calorie",
    "high-fiber",
]
additional_cuisine_types = [
    "Middle Eastern",
    "Vietnamese",
    "Thai",
    "Korean",
    "Japanese",
    "Chinese",
    "Indian",
    "Pakistani",
    "Bangladeshi",
    "Sri Lankan",
    "Indonesian",
    "Malaysian",
    "Filipino",
    "Caribbean",
    "African",
    "Ethiopian",
    "Moroccan",
    "Turkish",
    "Lebanese",
    "Persian",
    "Russian",
    "Eastern European",
    "Scandinavian",
    "German",
    "Austrian",
    "Swiss",
    "Belgian",
    "Dutch",
    "Portuguese",
    "Brazilian",
    "Peruvian",
    "Argentinian",
    "Cuban",
    "Jamaican",
    "Hawaiian",
    "Southern American",
    "Cajun",
    "Creole",
]
additional_user_personas = [
    "beginner cook",
    "experienced chef",
    "busy parent",
    "college student",
    "health enthusiast",
    "fitness trainer",
    "yoga instructor",
    "pregnant woman",
    "elderly person",
    "athlete",
    "bodybuilder",
    "weight loss seeker",
    "food blogger",
    "restaurant owner",
    "caterer",
    "meal prepper",
    "backpacker",
    "camping enthusiast",
    "picnic planner",
    "holiday host",
]

recipe_requests = [
    # Original requests
    # Clearly specified and feasible requests
    RecipeRequest(
        party_size="2",
        dietary_restrictions=["vegetarian"],
        cuisine_type="Italian",
        user_persona="date",
        scenario="clearly specified and feasible",
        natural_language_query="Can you suggest a romantic vegetarian Italian dinner recipe for a date night? Something that's not too complicated but still impressive.",
    ),
    RecipeRequest(
        party_size="4",
        dietary_restrictions=["gluten-free", "dairy-free"],
        cuisine_type="Mediterranean",
        user_persona="group",
        scenario="clearly specified and feasible",
        natural_language_query="I need a Mediterranean recipe that's both gluten-free and dairy-free for a dinner with friends. We're 4 people and I want something that's easy to make in bulk.",
    ),
    RecipeRequest(
        party_size="1",
        dietary_restrictions=["vegan"],
        cuisine_type="Japanese",
        user_persona="single",
        scenario="clearly specified and feasible",
        natural_language_query="I'm looking for a simple vegan Japanese recipe for one person. I'm cooking for myself and want something healthy but satisfying.",
    ),
    # Ambiguous or unclear requests
    RecipeRequest(
        party_size="6",
        dietary_restrictions=["halal"],
        cuisine_type="Indian",
        user_persona="party",
        scenario="ambiguous or unclear request",
        natural_language_query="I want to make something Indian for a party. What's good?",
    ),
    RecipeRequest(
        party_size="2",
        dietary_restrictions=["kosher"],
        cuisine_type="Greek",
        user_persona="couple",
        scenario="ambiguous or unclear request",
        natural_language_query="Can you help me make a Greek dish? I need it to be kosher but I'm not sure what would work.",
    ),
    RecipeRequest(
        party_size="9+",
        dietary_restrictions=["shellfish-free", "peanut-free"],
        cuisine_type="Chinese",
        user_persona="party",
        scenario="ambiguous or unclear request",
        natural_language_query="I'm hosting a big party and need to avoid shellfish and peanuts. Any ideas for Chinese food?",
    ),
    # Out of scope requests
    RecipeRequest(
        party_size="1",
        dietary_restrictions=["soy-free", "egg-free"],
        cuisine_type="Korean",
        user_persona="foodie",
        scenario="out of scope",
        natural_language_query="Can you create a completely new fusion recipe that combines Korean and Mexican flavors? I want something that's never been made before.",
    ),
    RecipeRequest(
        party_size="3",
        dietary_restrictions=["tree-nut-free"],
        cuisine_type="Thai",
        user_persona="group",
        scenario="out of scope",
        natural_language_query="I need a recipe that can be cooked in a microwave only, using only ingredients I can find in a gas station convenience store. Can you help?",
    ),
    RecipeRequest(
        party_size="2",
        dietary_restrictions=["vegetarian", "gluten-free"],
        cuisine_type="Spanish",
        user_persona="date",
        scenario="out of scope",
        natural_language_query="I want to make a molecular gastronomy dish for my date. Can you give me a recipe that uses liquid nitrogen and other scientific techniques?",
    ),
    RecipeRequest(
        party_size="4",
        dietary_restrictions=["dairy-free"],
        cuisine_type="French",
        user_persona="foodie",
        scenario="out of scope",
        natural_language_query="Can you help me recreate a dish from a 15th-century French cookbook? I want to make it exactly as it was made back then, using only ingredients and techniques available in medieval France.",
    ),
    # Additional 20 diverse requests
    RecipeRequest(
        party_size="1",
        dietary_restrictions=["vegetarian", "gluten-free"],
        cuisine_type="Indian",
        user_persona="single",
        scenario="clearly specified and feasible",
        natural_language_query="I'm looking for a simple vegetarian and gluten-free Indian recipe for one person. I'm new to Indian cooking but want to try making something authentic.",
    ),
    RecipeRequest(
        party_size="8",
        dietary_restrictions=["halal", "shellfish-free"],
        cuisine_type="Mediterranean",
        user_persona="party",
        scenario="clearly specified and feasible",
        natural_language_query="Need a Mediterranean recipe for 8 people that's halal and shellfish-free. It's for a family gathering and should be something that can be prepared ahead of time.",
    ),
    RecipeRequest(
        party_size="2",
        dietary_restrictions=["vegan"],
        cuisine_type="Japanese",
        user_persona="foodie",
        scenario="clearly specified and feasible",
        natural_language_query="Can you suggest an authentic vegan Japanese recipe for two foodies? We're experienced cooks and want to try something traditional but plant-based.",
    ),
    RecipeRequest(
        party_size="4",
        dietary_restrictions=["kosher", "dairy-free"],
        cuisine_type="Mexican",
        user_persona="group",
        scenario="clearly specified and feasible",
        natural_language_query="Looking for a kosher and dairy-free Mexican recipe for four people. We're a group of friends who love spicy food but need to keep it kosher.",
    ),
    RecipeRequest(
        party_size="6",
        dietary_restrictions=["peanut-free", "tree-nut-free"],
        cuisine_type="Thai",
        user_persona="party",
        scenario="clearly specified and feasible",
        natural_language_query="Need a Thai recipe for 6 people that's completely nut-free (both peanuts and tree nuts). It's for a dinner party and should be impressive but not too complicated.",
    ),
    RecipeRequest(
        party_size="1",
        dietary_restrictions=["soy-free"],
        cuisine_type="Korean",
        user_persona="single",
        scenario="ambiguous or unclear request",
        natural_language_query="I want to try making Korean food but I can't have soy. What can I make?",
    ),
    RecipeRequest(
        party_size="3",
        dietary_restrictions=["vegetarian"],
        cuisine_type="Chinese",
        user_persona="group",
        scenario="ambiguous or unclear request",
        natural_language_query="Can you suggest something Chinese for three vegetarians? We're not sure what would be good.",
    ),
    RecipeRequest(
        party_size="5",
        dietary_restrictions=["gluten-free"],
        cuisine_type="Italian",
        user_persona="party",
        scenario="ambiguous or unclear request",
        natural_language_query="I need a gluten-free Italian dish for a party of 5. What's easy to make?",
    ),
    RecipeRequest(
        party_size="2",
        dietary_restrictions=["dairy-free"],
        cuisine_type="French",
        user_persona="date",
        scenario="ambiguous or unclear request",
        natural_language_query="Looking for a dairy-free French recipe for a date night. Any suggestions?",
    ),
    RecipeRequest(
        party_size="4",
        dietary_restrictions=["vegan", "gluten-free"],
        cuisine_type="Mediterranean",
        user_persona="foodie",
        scenario="out of scope",
        natural_language_query="Can you create a completely new Mediterranean dish that's both vegan and gluten-free, using only ingredients that are currently in season in my local farmers market? I want something innovative that no one has ever made before.",
    ),
    RecipeRequest(
        party_size="9+",
        dietary_restrictions=["halal", "kosher"],
        cuisine_type="Indian",
        user_persona="party",
        scenario="out of scope",
        natural_language_query="I need a recipe that's both halal and kosher for a large wedding reception. It should be Indian cuisine but also appeal to guests who aren't familiar with Indian food.",
    ),
    RecipeRequest(
        party_size="1",
        dietary_restrictions=["shellfish-free"],
        cuisine_type="Japanese",
        user_persona="single",
        scenario="out of scope",
        natural_language_query="Can you help me make sushi at home without any special equipment? I'm allergic to shellfish but want to try making something authentic.",
    ),
    RecipeRequest(
        party_size="6",
        dietary_restrictions=["vegetarian", "vegan"],
        cuisine_type="Mexican",
        user_persona="group",
        scenario="clearly specified and feasible",
        natural_language_query="Need a vegan Mexican recipe for 6 people. We're a group of friends who love spicy food and want something that's both authentic and plant-based.",
    ),
    RecipeRequest(
        party_size="2",
        dietary_restrictions=["dairy-free", "egg-free"],
        cuisine_type="Greek",
        user_persona="couple",
        scenario="clearly specified and feasible",
        natural_language_query="Looking for a dairy-free and egg-free Greek recipe for two people. We're a couple who loves Mediterranean food but have dietary restrictions.",
    ),
    RecipeRequest(
        party_size="4",
        dietary_restrictions=["peanut-free", "tree-nut-free", "soy-free"],
        cuisine_type="Chinese",
        user_persona="group",
        scenario="clearly specified and feasible",
        natural_language_query="Need a Chinese recipe for 4 people that's free of peanuts, tree nuts, and soy. We're a group of friends with multiple allergies but love Chinese cuisine.",
    ),
    RecipeRequest(
        party_size="3",
        dietary_restrictions=["gluten-free", "dairy-free"],
        cuisine_type="Spanish",
        user_persona="foodie",
        scenario="clearly specified and feasible",
        natural_language_query="Can you suggest a gluten-free and dairy-free Spanish recipe for three foodies? We're experienced cooks and want something authentic but adapted to our dietary needs.",
    ),
    RecipeRequest(
        party_size="8",
        dietary_restrictions=["halal"],
        cuisine_type="Thai",
        user_persona="party",
        scenario="clearly specified and feasible",
        natural_language_query="Looking for a halal Thai recipe for 8 people. It's for a family gathering and should be something that can be prepared in advance.",
    ),
    RecipeRequest(
        party_size="1",
        dietary_restrictions=["vegetarian"],
        cuisine_type="Korean",
        user_persona="single",
        scenario="clearly specified and feasible",
        natural_language_query="I'm looking for a vegetarian Korean recipe for one person. I'm new to Korean cooking but want to try something authentic and healthy.",
    ),
    RecipeRequest(
        party_size="5",
        dietary_restrictions=["kosher"],
        cuisine_type="Italian",
        user_persona="group",
        scenario="clearly specified and feasible",
        natural_language_query="Need a kosher Italian recipe for 5 people. We're a group of friends who love Italian food and want to try something new while keeping it kosher.",
    ),
    RecipeRequest(
        party_size="2",
        dietary_restrictions=["vegan", "gluten-free"],
        cuisine_type="French",
        user_persona="date",
        scenario="clearly specified and feasible",
        natural_language_query="Can you suggest a vegan and gluten-free French recipe for a date night? We want something romantic and impressive but still manageable to cook together.",
    ),
    # Additional requests (continuing from previous list)
    RecipeRequest(
        party_size="family of 4",
        dietary_restrictions=["low-carb", "high-protein"],
        cuisine_type="Mexican",
        user_persona="busy parent",
        scenario="clearly specified and feasible",
        natural_language_query="Need a quick, low-carb, high-protein Mexican dinner recipe for my family of 4. I'm a busy parent who needs something that can be on the table in 30 minutes or less.",
    ),
    RecipeRequest(
        party_size="2-3",
        dietary_restrictions=["keto", "dairy-free"],
        cuisine_type="Thai",
        user_persona="health enthusiast",
        scenario="clearly specified and feasible",
        natural_language_query="Looking for a keto and dairy-free Thai recipe for 2-3 people. I'm following a strict ketogenic diet but still want to enjoy flavorful Asian cuisine.",
    ),
    RecipeRequest(
        party_size="1",
        dietary_restrictions=["paleo"],
        cuisine_type="Mediterranean",
        user_persona="fitness trainer",
        scenario="clearly specified and feasible",
        natural_language_query="I need a paleo Mediterranean recipe for one person. As a fitness trainer, I want something high in protein and healthy fats that I can meal prep for the week.",
    ),
    RecipeRequest(
        party_size="4-6",
        dietary_restrictions=["whole30", "gluten-free"],
        cuisine_type="Middle Eastern",
        user_persona="health enthusiast",
        scenario="clearly specified and feasible",
        natural_language_query="Can you suggest a Whole30 and gluten-free Middle Eastern recipe for 4-6 people? We're a group of health-conscious friends who love trying new cuisines.",
    ),
    RecipeRequest(
        party_size="7-9",
        dietary_restrictions=["low-sodium", "heart-healthy"],
        cuisine_type="Japanese",
        user_persona="elderly person",
        scenario="clearly specified and feasible",
        natural_language_query="Need a low-sodium, heart-healthy Japanese recipe for 7-9 people. It's for a family gathering where some members have heart conditions, but we still want to enjoy traditional Japanese flavors.",
    ),
    RecipeRequest(
        party_size="small gathering",
        dietary_restrictions=["pescatarian"],
        cuisine_type="Peruvian",
        user_persona="food blogger",
        scenario="clearly specified and feasible",
        natural_language_query="Looking for an impressive pescatarian Peruvian recipe for a small gathering. I'm a food blogger and want to create something photogenic but authentic for my readers.",
    ),
    RecipeRequest(
        party_size="college student",
        dietary_restrictions=["budget-friendly", "quick"],
        cuisine_type="Korean",
        user_persona="college student",
        scenario="clearly specified and feasible",
        natural_language_query="Need a budget-friendly and quick Korean recipe that a college student can make in a dorm kitchen. I want something authentic but with minimal equipment and ingredients.",
    ),
    RecipeRequest(
        party_size="2",
        dietary_restrictions=["low-FODMAP"],
        cuisine_type="Italian",
        user_persona="beginner cook",
        scenario="clearly specified and feasible",
        natural_language_query="Can you suggest a low-FODMAP Italian recipe for two people? I'm new to cooking and following a low-FODMAP diet for digestive health.",
    ),
    RecipeRequest(
        party_size="4",
        dietary_restrictions=["anti-inflammatory"],
        cuisine_type="Mediterranean",
        user_persona="health enthusiast",
        scenario="clearly specified and feasible",
        natural_language_query="Looking for an anti-inflammatory Mediterranean recipe for 4 people. We're focusing on foods that help reduce inflammation and promote overall health.",
    ),
    RecipeRequest(
        party_size="large gathering",
        dietary_restrictions=["diabetic-friendly"],
        cuisine_type="Indian",
        user_persona="holiday host",
        scenario="clearly specified and feasible",
        natural_language_query="Need a diabetic-friendly Indian recipe for a large gathering. I'm hosting a holiday party and want to ensure everyone can enjoy the food, including those with diabetes.",
    ),
    RecipeRequest(
        party_size="2-3",
        dietary_restrictions=["raw", "vegan"],
        cuisine_type="Thai",
        user_persona="yoga instructor",
        scenario="clearly specified and feasible",
        natural_language_query="Can you suggest a raw, vegan Thai recipe for 2-3 people? As a yoga instructor, I'm looking for something energizing and aligned with a holistic lifestyle.",
    ),
    RecipeRequest(
        party_size="family of 4",
        dietary_restrictions=["low-fat", "high-fiber"],
        cuisine_type="Mexican",
        user_persona="weight loss seeker",
        scenario="clearly specified and feasible",
        natural_language_query="Looking for a low-fat, high-fiber Mexican recipe for a family of 4. We're trying to eat healthier while still enjoying our favorite cuisine.",
    ),
    RecipeRequest(
        party_size="1",
        dietary_restrictions=["flexitarian"],
        cuisine_type="Japanese",
        user_persona="beginner cook",
        scenario="clearly specified and feasible",
        natural_language_query="I need a flexitarian Japanese recipe for one person. I'm new to cooking and trying to reduce meat consumption while learning Japanese cuisine.",
    ),
    RecipeRequest(
        party_size="4-6",
        dietary_restrictions=["low-calorie", "high-protein"],
        cuisine_type="Greek",
        user_persona="athlete",
        scenario="clearly specified and feasible",
        natural_language_query="Need a low-calorie, high-protein Greek recipe for 4-6 people. As an athlete, I want something that will help with muscle recovery and performance.",
    ),
    RecipeRequest(
        party_size="small gathering",
        dietary_restrictions=["gluten-free", "dairy-free"],
        cuisine_type="Vietnamese",
        user_persona="restaurant owner",
        scenario="clearly specified and feasible",
        natural_language_query="Looking for a gluten-free and dairy-free Vietnamese recipe for a small gathering. I own a restaurant and want to add some authentic Vietnamese dishes to our menu.",
    ),
    RecipeRequest(
        party_size="2",
        dietary_restrictions=["paleo", "whole30"],
        cuisine_type="Korean",
        user_persona="meal prepper",
        scenario="clearly specified and feasible",
        natural_language_query="Can you suggest a paleo and Whole30 Korean recipe for two people? I'm meal prepping for the week and want something that will keep well in the fridge.",
    ),
    RecipeRequest(
        party_size="camping",
        dietary_restrictions=["easy to transport"],
        cuisine_type="Mexican",
        user_persona="camping enthusiast",
        scenario="clearly specified and feasible",
        natural_language_query="Need a Mexican recipe that's easy to make while camping. I want something that's easy to transport and can be cooked over a campfire or portable stove.",
    ),
    RecipeRequest(
        party_size="picnic",
        dietary_restrictions=["no refrigeration needed"],
        cuisine_type="Mediterranean",
        user_persona="picnic planner",
        scenario="clearly specified and feasible",
        natural_language_query="Looking for a Mediterranean recipe that's perfect for a picnic. It should be something that doesn't need refrigeration and can be eaten cold or at room temperature.",
    ),
    RecipeRequest(
        party_size="2",
        dietary_restrictions=["pregnant woman safe"],
        cuisine_type="Japanese",
        user_persona="pregnant woman",
        scenario="clearly specified and feasible",
        natural_language_query="Can you suggest a Japanese recipe that's safe for pregnancy? I'm in my second trimester and craving Japanese food, but need to be careful about certain ingredients.",
    ),
    RecipeRequest(
        party_size="4",
        dietary_restrictions=["bodybuilder diet"],
        cuisine_type="Greek",
        user_persona="bodybuilder",
        scenario="clearly specified and feasible",
        natural_language_query="Need a Greek recipe that fits a bodybuilder's diet for 4 people. I'm looking for something high in protein and complex carbs that will support muscle growth.",
    ),
    # Additional 50 diverse requests with varied scenarios
    RecipeRequest(
        party_size="10-12",
        dietary_restrictions=["halal", "low-carb"],
        cuisine_type="Turkish",
        user_persona="caterer",
        scenario="ambiguous or unclear request",
        natural_language_query="I need some Turkish food ideas for a halal event. Should be low-carb but I'm not sure what would work best for a large group.",
    ),
    RecipeRequest(
        party_size="13-15",
        dietary_restrictions=["kosher", "heart-healthy"],
        cuisine_type="Lebanese",
        user_persona="holiday host",
        scenario="out of scope",
        natural_language_query="Can you help me create a fusion dish that combines traditional Lebanese flavors with molecular gastronomy techniques? It needs to be kosher and heart-healthy for a large holiday gathering.",
    ),
    RecipeRequest(
        party_size="16-20",
        dietary_restrictions=["vegan", "gluten-free"],
        cuisine_type="Persian",
        user_persona="restaurant owner",
        scenario="clearly specified and feasible",
        natural_language_query="Need a vegan and gluten-free Persian recipe that can be scaled up for 16-20 people. I want to add it to my restaurant's menu for large group bookings.",
    ),
    RecipeRequest(
        party_size="2-3",
        dietary_restrictions=["raw", "anti-inflammatory"],
        cuisine_type="Brazilian",
        user_persona="health enthusiast",
        scenario="ambiguous or unclear request",
        natural_language_query="I'm interested in raw Brazilian cuisine that's anti-inflammatory. What options are there for 2-3 people?",
    ),
    RecipeRequest(
        party_size="4-6",
        dietary_restrictions=["pescatarian", "low-FODMAP"],
        cuisine_type="Portuguese",
        user_persona="beginner cook",
        scenario="out of scope",
        natural_language_query="Can you help me create a modern interpretation of a traditional Portuguese seafood dish that's low-FODMAP? I'm new to cooking but want to try something innovative.",
    ),
    RecipeRequest(
        party_size="7-9",
        dietary_restrictions=["keto", "dairy-free"],
        cuisine_type="Russian",
        user_persona="experienced chef",
        scenario="clearly specified and feasible",
        natural_language_query="Looking for a keto and dairy-free Russian recipe for 7-9 people. I'm an experienced chef who wants to adapt traditional Russian cuisine to modern dietary needs.",
    ),
    RecipeRequest(
        party_size="small gathering",
        dietary_restrictions=["paleo", "high-protein"],
        cuisine_type="Argentinian",
        user_persona="fitness trainer",
        scenario="ambiguous or unclear request",
        natural_language_query="What are some paleo Argentinian options that would be high in protein? I'm planning a small gathering for my fitness clients.",
    ),
    RecipeRequest(
        party_size="large gathering",
        dietary_restrictions=["whole30", "anti-inflammatory"],
        cuisine_type="Moroccan",
        user_persona="caterer",
        scenario="out of scope",
        natural_language_query="I need to create a completely new Moroccan dish that's both Whole30 and anti-inflammatory for a large catering event. Can you help me develop something innovative?",
    ),
    RecipeRequest(
        party_size="family of 4",
        dietary_restrictions=["flexitarian", "low-sodium"],
        cuisine_type="Ethiopian",
        user_persona="busy parent",
        scenario="clearly specified and feasible",
        natural_language_query="Need a flexitarian and low-sodium Ethiopian recipe for my family of 4. As a busy parent, I want something that's both healthy and quick to prepare.",
    ),
    RecipeRequest(
        party_size="college student",
        dietary_restrictions=["budget-friendly", "high-fiber"],
        cuisine_type="Filipino",
        user_persona="college student",
        scenario="ambiguous or unclear request",
        natural_language_query="What Filipino dishes can I make in a dorm that are budget-friendly and high in fiber? I'm not sure what ingredients would be available.",
    ),
    RecipeRequest(
        party_size="2",
        dietary_restrictions=["diabetic-friendly", "low-fat"],
        cuisine_type="Indonesian",
        user_persona="elderly person",
        scenario="out of scope",
        natural_language_query="Can you help me create a diabetic-friendly version of a traditional Indonesian dish? I need it to be low in fat and suitable for someone managing diabetes.",
    ),
    RecipeRequest(
        party_size="4-6",
        dietary_restrictions=["raw", "vegan"],
        cuisine_type="Caribbean",
        user_persona="yoga instructor",
        scenario="clearly specified and feasible",
        natural_language_query="Looking for a raw, vegan Caribbean recipe for 4-6 people. As a yoga instructor, I want something that's both energizing and aligned with a holistic lifestyle.",
    ),
    RecipeRequest(
        party_size="7-9",
        dietary_restrictions=["low-calorie", "high-protein"],
        cuisine_type="Cuban",
        user_persona="athlete",
        scenario="ambiguous or unclear request",
        natural_language_query="What Cuban dishes would be good for athletes? I need something low-calorie but high in protein for my training group.",
    ),
    RecipeRequest(
        party_size="small gathering",
        dietary_restrictions=["gluten-free", "dairy-free"],
        cuisine_type="Jamaican",
        user_persona="food blogger",
        scenario="out of scope",
        natural_language_query="Can you help me create a gluten-free and dairy-free version of a traditional Jamaican dish that's never been made before? I want to feature it on my food blog.",
    ),
    RecipeRequest(
        party_size="large gathering",
        dietary_restrictions=["pescatarian", "heart-healthy"],
        cuisine_type="Hawaiian",
        user_persona="holiday host",
        scenario="clearly specified and feasible",
        natural_language_query="Need a pescatarian and heart-healthy Hawaiian recipe for a large holiday gathering. I want to serve something that's both traditional and good for heart health.",
    ),
    RecipeRequest(
        party_size="2-3",
        dietary_restrictions=["keto", "low-FODMAP"],
        cuisine_type="Southern American",
        user_persona="beginner cook",
        scenario="ambiguous or unclear request",
        natural_language_query="What Southern American dishes can be made keto and low-FODMAP? I'm new to cooking and need some guidance.",
    ),
    RecipeRequest(
        party_size="4",
        dietary_restrictions=["paleo", "anti-inflammatory"],
        cuisine_type="Cajun",
        user_persona="health enthusiast",
        scenario="out of scope",
        natural_language_query="Can you help me create a paleo and anti-inflammatory version of a traditional Cajun dish? I want to adapt it for modern health-conscious diners.",
    ),
    RecipeRequest(
        party_size="family of 4",
        dietary_restrictions=["whole30", "high-protein"],
        cuisine_type="Creole",
        user_persona="busy parent",
        scenario="clearly specified and feasible",
        natural_language_query="Need a Whole30 and high-protein Creole recipe for my family of 4. As a busy parent, I want something that's both nutritious and quick to prepare.",
    ),
    RecipeRequest(
        party_size="college student",
        dietary_restrictions=["budget-friendly", "low-carb"],
        cuisine_type="Pakistani",
        user_persona="college student",
        scenario="ambiguous or unclear request",
        natural_language_query="What Pakistani dishes can I make in a dorm that are budget-friendly and low-carb? I'm not sure what would work best.",
    ),
    RecipeRequest(
        party_size="2",
        dietary_restrictions=["diabetic-friendly", "high-fiber"],
        cuisine_type="Bangladeshi",
        user_persona="elderly person",
        scenario="out of scope",
        natural_language_query="Can you help me create a diabetic-friendly version of a traditional Bangladeshi dish? I need it to be high in fiber and suitable for someone managing diabetes.",
    ),
    RecipeRequest(
        party_size="4-6",
        dietary_restrictions=["raw", "anti-inflammatory"],
        cuisine_type="Sri Lankan",
        user_persona="yoga instructor",
        scenario="clearly specified and feasible",
        natural_language_query="Looking for a raw, anti-inflammatory Sri Lankan recipe for 4-6 people. As a yoga instructor, I want something that's both energizing and aligned with a holistic lifestyle.",
    ),
    RecipeRequest(
        party_size="7-9",
        dietary_restrictions=["low-calorie", "high-protein"],
        cuisine_type="Malaysian",
        user_persona="athlete",
        scenario="ambiguous or unclear request",
        natural_language_query="What Malaysian dishes would be good for athletes? I need something low-calorie but high in protein for my training group.",
    ),
    RecipeRequest(
        party_size="small gathering",
        dietary_restrictions=["gluten-free", "dairy-free"],
        cuisine_type="German",
        user_persona="food blogger",
        scenario="out of scope",
        natural_language_query="Can you help me create a gluten-free and dairy-free version of a traditional German dish that's never been made before? I want to feature it on my food blog.",
    ),
    RecipeRequest(
        party_size="large gathering",
        dietary_restrictions=["pescatarian", "heart-healthy"],
        cuisine_type="Austrian",
        user_persona="holiday host",
        scenario="clearly specified and feasible",
        natural_language_query="Need a pescatarian and heart-healthy Austrian recipe for a large holiday gathering. I want to serve something that's both traditional and good for heart health.",
    ),
    RecipeRequest(
        party_size="2-3",
        dietary_restrictions=["keto", "low-FODMAP"],
        cuisine_type="Swiss",
        user_persona="beginner cook",
        scenario="ambiguous or unclear request",
        natural_language_query="What Swiss dishes can be made keto and low-FODMAP? I'm new to cooking and need some guidance.",
    ),
    RecipeRequest(
        party_size="4",
        dietary_restrictions=["paleo", "anti-inflammatory"],
        cuisine_type="Belgian",
        user_persona="health enthusiast",
        scenario="out of scope",
        natural_language_query="Can you help me create a paleo and anti-inflammatory version of a traditional Belgian dish? I want to adapt it for modern health-conscious diners.",
    ),
    RecipeRequest(
        party_size="family of 4",
        dietary_restrictions=["whole30", "high-protein"],
        cuisine_type="Dutch",
        user_persona="busy parent",
        scenario="clearly specified and feasible",
        natural_language_query="Need a Whole30 and high-protein Dutch recipe for my family of 4. As a busy parent, I want something that's both nutritious and quick to prepare.",
    ),
    RecipeRequest(
        party_size="4",
        dietary_restrictions=[""],
        cuisine_type="Syrian",
        user_persona="Dinner host",
        scenario="clearly specified and feasible",
        natural_language_query="I am hosting a dinner party for 4 people. I want to serve a Syrian dish that is not too spicy and is easy to make. Ideally, the dish should include vegetables and red meat & a choice of multiple sauces.",
    ),
    RecipeRequest(
        party_size="4",
        dietary_restrictions=[""],
        cuisine_type="American",
        user_persona="Dinner host",
        scenario="clearly specified and feasible",
        natural_language_query="I am hosting a dinner party for 4 people. I want to serve an American dish pairs well with white wine and includes one type of protein and a variety of vegetables and carbohydrates.",
    ),
]

if __name__ == "__main__":
    for recipe_request in recipe_requests:
        print(
            f"#####\nresponse: {get_agent_response_with_metadata(recipe_request=recipe_request)}\n#####"
        )
